name: Start Services
description: Start Aztec local network (unless remote) and tee-rex server, then wait for health checks

inputs:
  aztec_node_url:
    description: Aztec node URL (local network started only when localhost)
    required: false
    default: "http://localhost:8080"
  prover_url:
    description: Prover URL for health check (local server started only when localhost)
    required: false
    default: "http://localhost:4000"

runs:
  using: composite
  steps:
    - name: Start Aztec local network
      if: inputs.aztec_node_url == 'http://localhost:8080'
      shell: bash
      env:
        FORGE_BROADCAST_TIMEOUT: "300"
      run: aztec start --local-network &

    - name: Start tee-rex server
      if: inputs.prover_url == 'http://localhost:4000'
      shell: bash
      run: bun run start &

    - name: Wait for Aztec node
      shell: bash
      env:
        AZTEC_NODE_URL: ${{ inputs.aztec_node_url }}
      run: |
        for i in $(seq 1 60); do
          if curl -sf "${AZTEC_NODE_URL}/status" > /dev/null 2>&1; then
            echo "Aztec node ready (attempt $i)"
            exit 0
          fi
          sleep 10
        done
        echo "Aztec node failed to respond at ${AZTEC_NODE_URL} within 10 minutes"
        exit 1

    - name: Wait for tee-rex server
      shell: bash
      env:
        PROVER_URL: ${{ inputs.prover_url }}
      run: |
        for i in $(seq 1 30); do
          if curl -sf "${PROVER_URL}/encryption-public-key" > /dev/null 2>&1; then
            echo "tee-rex server ready (attempt $i)"
            exit 0
          fi
          sleep 2
        done
        echo "tee-rex server failed to respond at ${PROVER_URL} within 1 minute"
        exit 1
