name: Setup Aztec
description: Install Bun, Foundry, and Aztec CLI. Version auto-detected from packages/sdk/package.json.

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
        restore-keys: ${{ runner.os }}-bun-

    - run: bun install --frozen-lockfile
      shell: bash

    - name: Detect Aztec version
      id: detect
      shell: bash
      run: |
        VERSION=$(bun -e "console.log(JSON.parse(require('fs').readFileSync('packages/sdk/package.json','utf8')).devDependencies['@aztec/aztec.js'])")
        echo "Aztec version: $VERSION"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Cache Aztec CLI
      id: cache-aztec
      uses: actions/cache@v4
      with:
        path: ~/.aztec/versions/${{ steps.detect.outputs.version }}
        key: ${{ runner.os }}-aztec-${{ steps.detect.outputs.version }}

    - name: Install Aztec CLI
      if: steps.cache-aztec.outputs.cache-hit != 'true'
      shell: bash
      run: |
        export CI=1
        export FOUNDRY_DIR="$HOME/.foundry"
        curl -fsSL "https://install.aztec.network/${{ steps.detect.outputs.version }}/install" \
          | VERSION=${{ steps.detect.outputs.version }} bash
        ls -la ~/.aztec/versions/${{ steps.detect.outputs.version }}/bin/

    - name: Update PATH
      shell: bash
      run: |
        echo "$HOME/.aztec/versions/${{ steps.detect.outputs.version }}/bin" >> $GITHUB_PATH
        echo "$HOME/.aztec/versions/${{ steps.detect.outputs.version }}/node_modules/.bin" >> $GITHUB_PATH
